name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip && pip install -r requirements.txt
      - run: pytest -v
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t crypto-converter .
  e2e:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d --build
      - run: |
          echo "Waiting for API to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:8000/health | grep -q "ok"; then
              echo "API is up!"
              exit 0
            fi
            sleep 5
          done
          exit 1
      - run: curl -s http://localhost:8000/convert?amount=1&from=BTC&to=USDT || true
