name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # minimal deps if no requirements.txt present
            pip install fastapi "sqlalchemy[asyncio]" aiosqlite \
                        pydantic pydantic-settings aiohttp httpx \
                        uvicorn pytest pytest-asyncio
          fi

      - name: Run tests
        env:
          # Safe defaults; tests mock external calls
          DATABASE_URL: sqlite+aiosqlite:///./tests/test_data/ci_tests.db
          BINANCE_WS_URL: wss://stream.binance.com:9443
          SUPPORTED_QUOTES: USDT,USDC
          QUOTE_SAVE_INTERVAL: "30"
          QUOTE_RETENTION_DAYS: "7"
          LOG_LEVEL: INFO
        run: pytest -v

  docker-build:
    name: Docker build (api & consumer)
    runs-on: ubuntu-latest
    needs: test  # only build if tests pass

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        run: |
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t crypto-converter:api-latest \
            .

      - name: Build Consumer image
        run: |
          # same Dockerfile, different default command is set by compose at runtime
          docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            -t crypto-converter:consumer-latest \
            .
